-- Generated by nwg-displays on 2026-06-26 at 15:35:52. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "1920x1200@60.0",
    position = "4446x2407",
    scale = 1.0
})
hl.monitor({
    output = "HDMI-A-1",
    mode = "3840x2160@60.0",
    position = "5455x967",
    scale = 1.5
})
