-- Generated by nwg-displays on 2026-06-17 at 12:58:25. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "3840x2400@59.99",
    position = "7999x2160",
    scale = 2.0
})
hl.monitor({
    output = "DP-2",
    mode = "3840x2160@60.0",
    position = "6079x2160",
    scale = 2.000000000000001
})
