[window]
opacity = 0.9

[font]
size = 14

[font.normal]
family = "JetBrains Mono"
style = "Regular"

[font.bold]
family = "JetBrains Mono"
style = "Bold"

[font.italic]
family = "JetBrains Mono"
style = "Italic"

[font.bold_italic]
family = "JetBrains Mono"
style = "Bold Italic"

[colors.primary]
background = "#161616"

[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\u001B\r"
